---
title: A Failed Attempt to Estimate the Causal Effect of Political Leadership
author: "Jonathan Mellon"
date: 2020-12-01T21:13:14-05:00
categories: ["R Markdown", "post-stratification", "response rate", "surveys", "weighting", "raking"]
tags: ["R Markdown", "post-stratification", "response rate", "surveys", "weighting", "raking"]
math: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The "file drawer" often refers to studies which authors don't publish because the results don't pan out the way they expected. This is most often used to talk about publication bias towards positive rather than null results. However, I find that my file drawer is full of research designs that sounded good in theory but then failed in practice. 

# Does Leadership Matter?

Public opinion and political behavior research is afflicted by endogeneity, particularly partisan endogeneity. In short, all the beliefs and attitudes (leaders, performance on issues, strength of identity, economic evaluations etc) that we think probably causally affect vote choice are likely to be influenced by an individual's partisan beliefs. If we see that Conservative party supporters have positive ratings of the economy, that might be because voters who think the economy is going well support the incumbent or it might just be because people who like the Conservative party want to believe and say things that make them look good.

Nowhere is this more true than leadership evaluations. There is an incredibly strong correlation between voters' evaluations of party leaders and voters' evaluations of the party. But of course, it may well be the case that a party's supporters naturally like the leader. After all, the party put that person in charge, so they must be great!

While the effect of leadership on party choice is robust to including lots of controls, 

So I thought I had a great idea of how to get around this problem. What if we could measure the ratings of a particular leader without the endogeneity created by the context of them being that party's leader. So we started fielding questions about important figures in the major UK parties in the innovation section of the British Election Study Internet Panel. 

As a result, we have measures of what British voters thought of Boris Johnson, Theresa May and Keir Starmer prior to each of them becoming party leader. We also asked about a number of other figures who we thought had a chance of being party leader which can act as controls for how much voters like figures in a party in general. 


Then we (me, Chris and Jack) actually got around to analyzing the data.




Now I am a [pretty big sceptic](https://files.osf.io/v1/resources/9qj4f/providers/osfstorage/60808cbe2952d800188d801b?action=download&direct&version=1) of a lot of instrumental variable work, but I wondered whether this might be a situation 




So, if anyone has any ideas about how to salvage this design, do let us know! 






